backend:
  name: github
  repo: Furaha-Systems/knowbank
  branch: main
  auth_scope: repo
  open_authoring: true

publish_mode: editorial_workflow

media_folder: "static/img"
public_folder: "/img/"

collections:
  - name: articles
    label: Articles
    folder: blog
    identifier_field: title
    extension: mdx
    format: frontmatter
    widget: list
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: title, label: Title, widget: string, required: true }
      - { name: body, label: Body, widget: markdown, required: true }
      - { name: slug, label: Slug, widget: string }
      - name: description
        label: Meta Description
        widget: string
        required: false
        hint: Description for SEO (by default uses first line of text below the frontmatter)
      - name: image
        label: Meta Image
        widget: string
        required: false
        hint: Image URL for SEO
      - name: enableComments
        label: Enable Comments
        widget: boolean
        default: false
      - name: tags
        label: Tags
        widget: list
      - name: authors
        label: Authors
        widget: list
        fields:
          - { name: key, label: Key, widget: string, required: false, hint: Global author key (only when directly writing to GitHub) }
          - { name: name, label: Name, widget: string, required: false }
          - { name: title, label: Title, widget: string, required: false } 
          - { name: url, label: URL, widget: string, required: false, hint: Link to author's page/profile } 
          - { name: image_url, label: Image URL, widget: string, required: false, hint: Url of author's profile image }
